# Generated by Django 3.1.2 on 2020-10-05 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roulette_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
            ],
        ),
    ]
