# Generated by Django 3.1.2 on 2020-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
