# Generated by Django 3.1.2 on 2020-10-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_roulette_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulette',
            name='status',
            field=models.CharField(blank=True, default='NEW', max_length=10),
        ),
    ]
