# Generated by Django 3.1.2 on 2020-10-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20201005_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='winner_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
